baseurl = "http://example.com"
title = "TruthsBeTold"
theme = "hugo-coder"
languagecode = "cn"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "David"
  info = " 每个真诚的心都会被上帝所指引！"
  description = "David's personal website"
  keywords = "life,tech,personal"
  avatarurl = "https://raw.githubusercontent.com/davidwww523/photo/master/me.jpg"
  #gravatar = ""

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/davidwww523/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://Instagram.com/kingwl/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/kingwl/"

# Menu links
[[menu.main]]
  name = "Life"
  weight = 1
  url  = "life/"
[[menu.main]]
  name = "Tech"
  weight = 2
  url  = "tech/"
[[menu.main]]
  name = "Politic"
  weight = 3
  url  = "poli/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"